### ISSUE TITLE
DBのポートが露呈している

### ISSUE THREAD

**Issue by defaultcf** [uehara1414/serverctl-prototype#1]
```
ports:
    - "5432:5432"
```
この記述でセキュリティ上のリスクが無駄に発生しています。
Docker間の接続は外部にポートを晒さずとも出来るので、この記述は不要です。

**Comment by defaultcf** [comment]
#3 
@uehara1414 添削してください(言うて2行消しただけ)

**Comment by uehara1414** [comment]
@i544c コミットメセージに#3とかのissue番号を入れると自動で紐づけられて、そのコミットを含むプルリクがマージされた時に同時にそのissueも閉じられるようになるよ
活用すべし

**Comment by defaultcf** [comment]
@uehara1414 マジかスゲェ
荒らしてゴメン

**Comment by uehara1414** [comment]
いやいや、頼りにしておるぞ

**Comment by uehara1414** [comment]
外部ポートは、[Postico](https://eggerapps.at/postico/)使って直に見たり操作したりすることあるから開けさせてくださいお願いします。

**Comment by defaultcf** [comment]
それはローカルの話だし、リポジトリ上はあの記述は消しておいて良いのでは...
一々ステージングから外すの面倒だ、っていうなら`docker-compose.yml`を`assume-unchanged`してほしい...
[参考資料](http://qiita.com/usamik26/items/56d0d3ba7a1300625f92)

**Comment by uehara1414** [comment]
ほう、そんな設定が・・・
私はしばらくは手元の環境でごちゃごちゃ実験するだけなので、今はデプロイまで考えて細かい設定する気はないゆえ、そこらへんの設定とか全部任せちゃっていいですか

**Comment by uehara1414** [comment]
`docker-compose.yml` は `assume-unchanged`にして見ます

**Comment by defaultcf** [comment]
あい

**Comment by uehara1414** [comment]
issue閉じまーす
